### ISSUE TITLE
ELS not working

### ISSUE THREAD

**Issue by IslandNull** [attitus3/OpenVHook#23]
I'm using commit 1a80cdb and Rockstar Launcher, every script works fine except ELS.

**OpenVHook.log:**

[20:16:04] Kept OpenVHook reference: 00007FF974830000
[20:16:04] Registering script 'ELS.asi' (0x00007FF99E4D0000!0x00007FF99E5050E0)
[20:16:04] Initializing...
[20:16:04] Registering script 'NativeTrainer.asi' (0x00007FF9CC300000!0x00007FF9CC30A3C0)
[20:16:04] Registering script 'OpenInteriors.asi' (0x00007FF9C83F0000!0x00007FF9C83FB950)
[20:16:04] Registering script 'PLD.asi' (0x00007FF9C66A0000!0x00007FF9C66A4EF0)
[20:16:05] Input hook attached: WndProc 0x00000000FFFF0CB9
[20:16:05] Initializing ScriptEngine...
[20:16:10] Game version is 76
[20:16:10] Initializing Pools...
[20:16:12] Pool Init Finished
[20:16:12] Checking if game is ready...
[20:16:15] Game ready
[20:16:15] Registering script 'ELS.asi' (0x00007FF99E4D0000!0x00007FF99E5050E0)
[20:16:15] Registering script 'PLD.asi' (0x00007FF9C66A0000!0x00007FF9C66A4EF0)
[20:16:15] Registering script 'OpenInteriors.asi' (0x00007FF9C83F0000!0x00007FF9C83FB950)
[20:16:15] Registering script 'NativeTrainer.asi' (0x00007FF9CC300000!0x00007FF9CC30A3C0)
[20:16:15] Initialization finished
[20:17:45] Launching script ELS.asi
[20:17:45] Launching script PLD.asi
[20:17:45] Launching script OpenInteriors.asi
[20:17:45] Launching script NativeTrainer.asi
[20:18:14] [Error] Error in script->Run ELS.asi

**asiloader.log**
// GTA V ASI LOADER (build May  2 2015)
//     (C) Alexander Blade 2015
LIB: "C:\WINDOWS\system32\dinput8.dll" => 00007FF9E7AB0000
API: "DirectInput8Create" => 00007FF9E7AB2230
API: "DllCanUnloadNow" => 00007FF9E7AC5220
API: "DllGetClassObject" => 00007FF9E7AC5330
API: "DllRegisterServer" => 00007FF9E7AD4740
API: "DllUnregisterServer" => 00007FF9E7AD49C0
LOADER: Loading *.asi plugins
ASI: Loading "D:\JOGOS\Grand Theft Auto V\ELS.asi"
     "ELS.asi" => 00007FF99E4D0000
ASI: Loading "D:\JOGOS\Grand Theft Auto V\HeapAdjuster.asi"
     "HeapAdjuster.asi" => 00007FF9D1FF0000
ASI: Loading "D:\JOGOS\Grand Theft Auto V\NativeTrainer.asi"
     "NativeTrainer.asi" => 00007FF9CC300000
ASI: Loading "D:\JOGOS\Grand Theft Auto V\openCameraV.asi"
     "openCameraV.asi" => 00007FF9E7FD0000
ASI: Loading "D:\JOGOS\Grand Theft Auto V\OpenInteriors.asi"
     "OpenInteriors.asi" => 00007FF9C83F0000
ASI: Loading "D:\JOGOS\Grand Theft Auto V\OpenIV.asi"
     "OpenIV.asi" => 00007FF9E7E40000
ASI: Loading "D:\JOGOS\Grand Theft Auto V\PLD.asi"
     "PLD.asi" => 00007FF9C66A0000
LOADER: Finished loading *.asi plugins

**AdvancedHook.log**

AdvancedHookV 0.1 by LMS
Base: 0x7FF6C4C70000 -- Size: 0x48E9C00
Service requested from ELS

**ELS.log**

 
<AHOOK> Attempting to initialize AdvancedHookV by LMS.
	(OK) AdvancedHookV.dll file found and successfully initialized.
<FILEG> Collecting information from ELS.ini.
	(OK) Main configuration data successfully collected.
<VCONT> Attempting to open VCF container at: [ .//ELS//pack_default ].
	(OK) VCF container found, scanning for files.
<FILEV> Found file: [ fbi.xml ].
<FILEV> Verifying vehicle model name [ fbi ].
	(OK) Is valid vehicle model, assigned VMID [ 0 ].
	     Parsing file. *A crash before all clear indicates faulty VCF.*
	     VCF Description: LAPD Unmarked
	     VCF Author: (null)
			(OK) Collected data from: 'ADMIN'.
			(OK) Collected data from: 'INTERFACE'.
			(OK) Collected data from: 'EOVERRIDE'.
			(OK) Collected data from: 'MISC'.
			(OK) Collected data from: 'CRUISE'.
			(OK) Collected data from: 'ACORONAS'.
			(OK) Collected data from: 'SOUNDS'.
			(OK) Collected data from: 'WRNL'.
			(OK) Collected data from: 'PRML'.
			(OK) Collected data from: 'SECL'.
			(OK) ALL CLEAR -- Configuration file processed.
<FILEV> Found file: [ fbi2.xml ].
<FILEV> Verifying vehicle model name [ fbi2 ].
	(OK) Is valid vehicle model, assigned VMID [ 1 ].
	     Parsing file. *A crash before all clear indicates faulty VCF.*
	     VCF Description: LAPD Unmarked
	     VCF Author: (null)
			(OK) Collected data from: 'ADMIN'.
			(OK) Collected data from: 'INTERFACE'.
			(OK) Collected data from: 'EOVERRIDE'.
			(OK) Collected data from: 'MISC'.
			(OK) Collected data from: 'CRUISE'.
			(OK) Collected data from: 'ACORONAS'.
			(OK) Collected data from: 'SOUNDS'.
			(OK) Collected data from: 'WRNL'.
			(OK) Collected data from: 'PRML'.
			(OK) Collected data from: 'SECL'.
			(OK) ALL CLEAR -- Configuration file processed.
<FILEV> Found file: [ police.xml ].
<FILEV> Verifying vehicle model name [ police ].
	(OK) Is valid vehicle model, assigned VMID [ 2 ].
	     Parsing file. *A crash before all clear indicates faulty VCF.*
	     VCF Description: Sample VCF
	     VCF Author: Luxart
			(OK) Collected data from: 'ADMIN'.
			(OK) Collected data from: 'INTERFACE'.
			(OK) Collected data from: 'EOVERRIDE'.
			(OK) Collected data from: 'MISC'.
			(OK) Collected data from: 'CRUISE'.
			(OK) Collected data from: 'ACORONAS'.
			(OK) Collected data from: 'SOUNDS'.
			(OK) Collected data from: 'WRNL'.
			(OK) Collected data from: 'PRML'.
			(OK) Collected data from: 'SECL'.
			(OK) ALL CLEAR -- Configuration file processed.
<FILEV> Found file: [ police1.xml ].
<FILEV> Verifying vehicle model name [ police1 ].
	(OK) Is valid vehicle model, assigned VMID [ 3 ].
	     Parsing file. *A crash before all clear indicates faulty VCF.*
	     VCF Description: LAPD Detective/Slicktop
	     VCF Author: (null)
			(OK) Collected data from: 'ADMIN'.
			(OK) Collected data from: 'INTERFACE'.
			(OK) Collected data from: 'EOVERRIDE'.
			(OK) Collected data from: 'MISC'.
			(OK) Collected data from: 'CRUISE'.
			(OK) Collected data from: 'ACORONAS'.
			(OK) Collected data from: 'SOUNDS'.
			(OK) Collected data from: 'WRNL'.
			(OK) Collected data from: 'PRML'.
			(OK) Collected data from: 'SECL'.
			(OK) ALL CLEAR -- Configuration file processed.
<FILEV> Found file: [ police12.xml ].
<FILEV> Verifying vehicle model name [ police12 ].
	(OK) Is valid vehicle model, assigned VMID [ 4 ].
	     Parsing file. *A crash before all clear indicates faulty VCF.*
	     VCF Description: LAPD Arjent
	     VCF Author: (null)
			(OK) Collected data from: 'ADMIN'.
			(OK) Collected data from: 'INTERFACE'.
			(OK) Collected data from: 'EOVERRIDE'.
			(OK) Collected data from: 'MISC'.
			(OK) Collected data from: 'CRUISE'.
			(OK) Collected data from: 'ACORONAS'.
			(OK) Collected data from: 'SOUNDS'.
			(OK) Collected data from: 'WRNL'.
			(OK) Collected data from: 'PRML'.
			(OK) Collected data from: 'SECL'.
			(OK) ALL CLEAR -- Configuration file processed.
<FILEV> Found file: [ police2.xml ].
<FILEV> Verifying vehicle model name [ police2 ].
	(OK) Is valid vehicle model, assigned VMID [ 5 ].
	     Parsing file. *A crash before all clear indicates faulty VCF.*
	     VCF Description: LAPD Arjent
	     VCF Author: (null)
			(OK) Collected data from: 'ADMIN'.
			(OK) Collected data from: 'INTERFACE'.
			(OK) Collected data from: 'EOVERRIDE'.
			(OK) Collected data from: 'MISC'.
			(OK) Collected data from: 'CRUISE'.
			(OK) Collected data from: 'ACORONAS'.
			(OK) Collected data from: 'SOUNDS'.
			(OK) Collected data from: 'WRNL'.
			(OK) Collected data from: 'PRML'.
			(OK) Collected data from: 'SECL'.
			(OK) ALL CLEAR -- Configuration file processed.
<FILEV> Found file: [ police21.xml ].
<FILEV> Verifying vehicle model name [ police21 ].
	(OK) Is valid vehicle model, assigned VMID [ 6 ].
	     Parsing file. *A crash before all clear indicates faulty VCF.*
	     VCF Description: LAPD Valor
	     VCF Author: (null)
			(OK) Collected data from: 'ADMIN'.
			(OK) Collected data from: 'INTERFACE'.
			(OK) Collected data from: 'EOVERRIDE'.
			(OK) Collected data from: 'MISC'.
			(OK) Collected data from: 'CRUISE'.
			(OK) Collected data from: 'ACORONAS'.
			(OK) Collected data from: 'SOUNDS'.
			(OK) Collected data from: 'WRNL'.
			(OK) Collected data from: 'PRML'.
			(OK) Collected data from: 'SECL'.
			(OK) ALL CLEAR -- Configuration file processed.
<FILEV> Found file: [ police22.xml ].
<FILEV> Verifying vehicle model name [ police22 ].
	(OK) Is valid vehicle model, assigned VMID [ 7 ].
	     Parsing file. *A crash before all clear indicates faulty VCF.*
	     VCF Description: LAPD Detective/Slicktop/Takedown Enabled
	     VCF Author: (null)
			(OK) Collected data from: 'ADMIN'.
			(OK) Collected data from: 'INTERFACE'.
			(OK) Collected data from: 'EOVERRIDE'.
			(OK) Collected data from: 'MISC'.
			(OK) Collected data from: 'CRUISE'.
			(OK) Collected data from: 'ACORONAS'.
			(OK) Collected data from: 'SOUNDS'.
			(OK) Collected data from: 'WRNL'.
			(OK) Collected data from: 'PRML'.
			(OK) Collected data from: 'SECL'.
			(OK) ALL CLEAR -- Configuration file processed.
<FILEV> Found file: [ police23.xml ].
<FILEV> Verifying vehicle model name [ police23 ].
	(OK) Is valid vehicle model, assigned VMID [ 8 ].
	     Parsing file. *A crash before all clear indicates faulty VCF.*
	     VCF Description: LAPD Arjent
	     VCF Author: (null)
			(OK) Collected data from: 'ADMIN'.
			(OK) Collected data from: 'INTERFACE'.
			(OK) Collected data from: 'EOVERRIDE'.
			(OK) Collected data from: 'MISC'.
			(OK) Collected data from: 'CRUISE'.
			(OK) Collected data from: 'ACORONAS'.
			(OK) Collected data from: 'SOUNDS'.
			(OK) Collected data from: 'WRNL'.
			(OK) Collected data from: 'PRML'.
			(OK) Collected data from: 'SECL'.
			(OK) ALL CLEAR -- Configuration file processed.
<FILEV> Found file: [ police3.xml ].
<FILEV> Verifying vehicle model name [ police3 ].
	(OK) Is valid vehicle model, assigned VMID [ 9 ].
	     Parsing file. *A crash before all clear indicates faulty VCF.*
	     VCF Description: LAPD Arjent
	     VCF Author: (null)
			(OK) Collected data from: 'ADMIN'.
			(OK) Collected data from: 'INTERFACE'.
			(OK) Collected data from: 'EOVERRIDE'.
			(OK) Collected data from: 'MISC'.
			(OK) Collected data from: 'CRUISE'.
			(OK) Collected data from: 'ACORONAS'.
			(OK) Collected data from: 'SOUNDS'.
			(OK) Collected data from: 'WRNL'.
			(OK) Collected data from: 'PRML'.
			(OK) Collected data from: 'SECL'.
			(OK) ALL CLEAR -- Configuration file processed.
<FILEV> Found file: [ police4.xml ].
<FILEV> Verifying vehicle model name [ police4 ].
	(OK) Is valid vehicle model, assigned VMID [ 10 ].
	     Parsing file. *A crash before all clear indicates faulty VCF.*
	     VCF Description: LAPD Detective/Slicktop
	     VCF Author: (null)
			(OK) Collected data from: 'ADMIN'.
			(OK) Collected data from: 'INTERFACE'.
			(OK) Collected data from: 'EOVERRIDE'.
			(OK) Collected data from: 'MISC'.
			(OK) Collected data from: 'CRUISE'.
			(OK) Collected data from: 'ACORONAS'.
			(OK) Collected data from: 'SOUNDS'.
			(OK) Collected data from: 'WRNL'.
			(OK) Collected data from: 'PRML'.
			(OK) Collected data from: 'SECL'.
			(OK) ALL CLEAR -- Configuration file processed.
<FILEV> Found file: [ police41.xml ].
<FILEV> Verifying vehicle model name [ police41 ].
	(OK) Is valid vehicle model, assigned VMID [ 11 ].
	     Parsing file. *A crash before all clear indicates faulty VCF.*
	     VCF Description: LAPD Detective/Slicktop
	     VCF Author: (null)
			(OK) Collected data from: 'ADMIN'.
			(OK) Collected data from: 'INTERFACE'.
			(OK) Collected data from: 'EOVERRIDE'.
			(OK) Collected data from: 'MISC'.
			(OK) Collected data from: 'CRUISE'.
			(OK) Collected data from: 'ACORONAS'.
			(OK) Collected data from: 'SOUNDS'.
			(OK) Collected data from: 'WRNL'.
			(OK) Collected data from: 'PRML'.
			(OK) Collected data from: 'SECL'.
			(OK) ALL CLEAR -- Configuration file processed.
<FILEV> Found file: [ police5.xml ].
<FILEV> Verifying vehicle model name [ police5 ].
	(OK) Is valid vehicle model, assigned VMID [ 12 ].
	     Parsing file. *A crash before all clear indicates faulty VCF.*
	     VCF Description: LAPD Arjent
	     VCF Author: (null)
			(OK) Collected data from: 'ADMIN'.
			(OK) Collected data from: 'INTERFACE'.
			(OK) Collected data from: 'EOVERRIDE'.
			(OK) Collected data from: 'MISC'.
			(OK) Collected data from: 'CRUISE'.
			(OK) Collected data from: 'ACORONAS'.
			(OK) Collected data from: 'SOUNDS'.
			(OK) Collected data from: 'WRNL'.
			(OK) Collected data from: 'PRML'.
			(OK) Collected data from: 'SECL'.
			(OK) ALL CLEAR -- Configuration file processed.
<FILEV> Found file: [ police6.xml ].
<FILEV> Verifying vehicle model name [ police6 ].
	(OK) Is valid vehicle model, assigned VMID [ 13 ].
	     Parsing file. *A crash before all clear indicates faulty VCF.*
	     VCF Description: LAPD Arjent/Signalmaster
	     VCF Author: (null)
			(OK) Collected data from: 'ADMIN'.
			(OK) Collected data from: 'INTERFACE'.
			(OK) Collected data from: 'EOVERRIDE'.
			(OK) Collected data from: 'MISC'.
			(OK) Collected data from: 'CRUISE'.
			(OK) Collected data from: 'ACORONAS'.
			(OK) Collected data from: 'SOUNDS'.
			(OK) Collected data from: 'WRNL'.
			(OK) Collected data from: 'PRML'.
			(OK) Collected data from: 'SECL'.
			(OK) ALL CLEAR -- Configuration file processed.
<FILEV> Found file: [ police61.xml ].
<FILEV> Verifying vehicle model name [ police61 ].
	(OK) Is valid vehicle model, assigned VMID [ 14 ].
	     Parsing file. *A crash before all clear indicates faulty VCF.*
	     VCF Description: LAPD Valor/Signalmaster
	     VCF Author: (null)
			(OK) Collected data from: 'ADMIN'.
			(OK) Collected data from: 'INTERFACE'.
			(OK) Collected data from: 'EOVERRIDE'.
			(OK) Collected data from: 'MISC'.
			(OK) Collected data from: 'CRUISE'.
			(OK) Collected data from: 'ACORONAS'.
			(OK) Collected data from: 'SOUNDS'.
			(OK) Collected data from: 'WRNL'.
			(OK) Collected data from: 'PRML'.
			(OK) Collected data from: 'SECL'.
			(OK) ALL CLEAR -- Configuration file processed.
<FILEV> Found file: [ police7.xml ].
<FILEV> Verifying vehicle model name [ police7 ].
	(OK) Is valid vehicle model, assigned VMID [ 15 ].
	     Parsing file. *A crash before all clear indicates faulty VCF.*
	     VCF Description: LAPD Valor/Signalmaster
	     VCF Author: (null)
			(OK) Collected data from: 'ADMIN'.
			(OK) Collected data from: 'INTERFACE'.
			(OK) Collected data from: 'EOVERRIDE'.
			(OK) Collected data from: 'MISC'.
			(OK) Collected data from: 'CRUISE'.
			(OK) Collected data from: 'ACORONAS'.
			(OK) Collected data from: 'SOUNDS'.
			(OK) Collected data from: 'WRNL'.
			(OK) Collected data from: 'PRML'.
			(OK) Collected data from: 'SECL'.
			(OK) ALL CLEAR -- Configuration file processed.
<FILEV> Found file: [ police71.xml ].
<FILEV> Verifying vehicle model name [ police71 ].
	(OK) Is valid vehicle model, assigned VMID [ 16 ].
	     Parsing file. *A crash before all clear indicates faulty VCF.*
	     VCF Description: LAPD Arjent
	     VCF Author: (null)
			(OK) Collected data from: 'ADMIN'.
			(OK) Collected data from: 'INTERFACE'.
			(OK) Collected data from: 'EOVERRIDE'.
			(OK) Collected data from: 'MISC'.
			(OK) Collected data from: 'CRUISE'.
			(OK) Collected data from: 'ACORONAS'.
			(OK) Collected data from: 'SOUNDS'.
			(OK) Collected data from: 'WRNL'.
			(OK) Collected data from: 'PRML'.
			(OK) Collected data from: 'SECL'.
			(OK) ALL CLEAR -- Configuration file processed.
<FILEV> Found file: [ police8.xml ].
<FILEV> Verifying vehicle model name [ police8 ].
	(OK) Is valid vehicle model, assigned VMID [ 17 ].
	     Parsing file. *A crash before all clear indicates faulty VCF.*
	     VCF Description: LAPD Arjent/Signalmaster
	     VCF Author: (null)
			(OK) Collected data from: 'ADMIN'.
			(OK) Collected data from: 'INTERFACE'.
			(OK) Collected data from: 'EOVERRIDE'.
			(OK) Collected data from: 'MISC'.
			(OK) Collected data from: 'CRUISE'.
			(OK) Collected data from: 'ACORONAS'.
			(OK) Collected data from: 'SOUNDS'.
			(OK) Collected data from: 'WRNL'.
			(OK) Collected data from: 'PRML'.
			(OK) Collected data from: 'SECL'.
			(OK) ALL CLEAR -- Configuration file processed.
<FILEV> Vehicle information retrieved. Loaded [ 18 ] ELS-enabled model(s).

**Comment by GuiShing** [comment]
So, you are not using Steam or Epic?
Apparently this openhook works mostly for Epic users.

**Comment by peterevertz** [comment]
> So, you are not using Steam or Epic? Apparently this openhook works mostly for Epic users.

The version for steam is fixed (at least for me)
https://github.com/attitus3/OpenVHook/issues/21#issuecomment-1139999591

**Comment by DwemerEngineer** [comment]
This is likely the result of vehicle pools still not working completely right, its an ongoing issue. It is currently what I am focusing on resolving.
